name: google_map_location_picker
description: 'ðŸŒ Map location picker for flutter Based on google_maps_flutter'
version: 6.0.1
homepage: https://github.com/apps-auth/modern_form_google_map_location_picker.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0 <1.0.0'

  flutter_keyboard_visibility: ">=5.0.3 <6.0.0"
  google_maps_flutter: '>=2.2.8 <3.0.0'
  geolocator: '>=9.0.2 <10.0.0'
  android_intent_plus: '>=4.0.1 <5.0.0'
  provider: '>=6.0.5 <7.0.0'
  http: '>=1.0.0 <2.0.0'
  stack_trace: '>=1.11.0 <2.0.0'
  package_info_plus: '>=4.0.2 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      # This plugin project was generated without specifying any
      # platforms with the `--platform` argument. If you see the `fake_platform` map below, remove it and
      # then add platforms following the instruction here:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
      android:
        package: com.humazed.google_map_location_picker
        pluginClass: GoogleMapLocationPickerPlugin
    # -------------------

flutter_intl:
  enabled: true